### ISSUE TITLE
Rename config files to "sample" files

### ISSUE THREAD

**Issue by joserprieto** [Tecnativa/docker-odoo-base#102]
I think that is much better to rename the different config files on the scaffolding, to a ".sample." files, for get the repo clean and allow an easy update of this (as a submodule of another project, for example).

I go to explain this a little better.

I have right now, one repo, with this directory structure:

```
.
├── docker
│   ├── common.yaml
│   ├── devel.yaml
│   ├── docker-compose.yml -> devel.yaml
│   ├── inverseproxy.yaml
│   ├── LICENSE
│   ├── odoo
│   │   ├── auto
│   │   │   └── addons
│   │   ├── custom
│   │   │   ├── build.d
│   │   │   ├── conf.d
│   │   │   ├── dependencies
│   │   │   ├── entrypoint.d
│   │   │   ├── src
│   │   │   └── ssh
│   │   └── Dockerfile
│   ├── prod.yaml
│   ├── README.md
│   ├── setup-devel.yaml
│   ├── src -> ./odoo/custom/src/
│   └── test.yaml
└── README.md
```

the "docker" folder, is a submodule (git submodule add git@github.com:Tecnativa/docker-odoo-base.git ./docker); but, logically, i have to configure same files for my custom installation; there are (i put them refered to the tecnativa odoo base docker scaffolding):

```
./odoo/Dockerfile
./odoo/custom/dependencies/apt_build.txt
./odoo/custom/dependencies/apt.txt
./odoo/custom/dependencies/gem.txt
./odoo/custom/dependencies/npm.txt
./odoo/custom/dependencies/pip.txt
./odoo/custom/src/addons.yaml
./odoo/custom/src/repos.yaml
./odoo/custom/ssh/config
./odoo/custom/ssh/id_rsa
./odoo/custom/ssh/id_rsa.pub
./odoo/custom/ssh/known_hosts
```

With all of these files commited, if i change any of this, for my own needs, like.. Simply, install the prestapyt python module, for example (has to be on the pip.txt), i will can't make a pull after that.

If the versioned files were something like this:

```
./odoo/Dockerfile.sample
./odoo/custom/dependencies/apt_build.txt.sample
./odoo/custom/dependencies/apt.txt.sample
./odoo/custom/dependencies/gem.txt.sample
./odoo/custom/dependencies/npm.txt.sample
./odoo/custom/dependencies/pip.txt.sample
./odoo/custom/src/addons.yaml.sample
./odoo/custom/src/repos.yaml.sample
./odoo/custom/ssh/config.sample
./odoo/custom/ssh/id_rsa.sample
./odoo/custom/ssh/id_rsa.pub.sample
./odoo/custom/ssh/known_hosts.sample
```

And has entries for the really config files mentioned above on the .gitignore of the repo, all of us can adapt the repo to our needs, and not have to get the config files, get outside repo, make the pull of the repo, and put into repo the config files again.

The YAML docker-compose files don't need something like that, because in the scaffolding aren't a docker-compose.yml file (the README say that we have to make a simbolic link).

What do you think?

If you like, i can make a PR.

Regards.

PD: may be useful un bash script to rename or copy the .sample files renamed  into their locations. I can make it too, if you like.

**Comment by Yajo** [comment]
The purpose of our scaffolding is not to be used as a submodule, but as a whole project structure updatable template. It defines how your files layout should be. It doesn't make sense to provide .sample files and git-ignore the real files, because what you actually want to have versioned are the real files, not the samples.

As it is right now, the scaffolding works out of the box by just `git clone`, and `docker-compose -f test.yaml up`, and that's the newcomer experience we want to give (or make it even simpler if possible, but never less).

You propose a different project directory layout that makes a different usage of the scaffolding, and mixing both would lead to problems.

If you consider the current scaffolding experience is not good enough, you can have your own scaffolding. You can even publish it also, and if you ping us we can include a link in the README in a new "alternative scaffoldings" section. That would be awesome. 😉 

But not, this is not an *improvement* AFAICS, and that's not what the official scaffolding will become. As a personal side opinion, I never liked projects that supply .sample files that I have to copy and paste; I'm more on the "it should work out of the box" side of the discussion.

Thanks!
