### ISSUE TITLE
Openupgradelib not compatible (caused by new rename_fields method)

### ISSUE THREAD

**Issue by sfeilmeier** [Tecnativa/docker-odoo-base#103]
Hello,

first of all I would like to thank you for this great piece of software. While the learning curve was steep and not everything is working perfectly in my case yet, it is still tremendously valuable.

For the issue I am not sure where it fits best. It involves [OpenUpgrade](https://github.com/OCA/OpenUpgrade), [openupgradelib](https://github.com/OCA/openupgradelib) and (docker-odoo-base)[https://github.com/Tecnativa/docker-odoo-base]. Because I was able to bugfix it in docker-odoo-base, I am posting it here.

Since introduction of the "rename_fields" in openupgradelib and changes in migration scripts, OpenUpgrade crashes with an error "'module' object has no attribute 'rename_fields'". The problem is caused by https://github.com/Tecnativa/docker-odoo-base/blob/master/8.0.Dockerfile#L120 which installs the latest version of openupgradelib from pip. This release does not yet contain the "rename_fields" method. 

I was able to fix this issue by creating my own copy of 8.0.Dockerfile and replacing "openupgradelib" with "git+https://github.com/OCA/openupgradelib.git@master".

Best Regards.

**Comment by pedrobaeza** [comment]
That's not needed. Simply put in your pip.txt file of your scaffolding:
```
git+https://github.com/OCA/openupgradelib.git@master
```
And it will be used as the final version in your Docker instance.

**Comment by sfeilmeier** [comment]
Ok, learned something new again. Thank you for the solution and the very fast reply!

**Comment by Yajo** [comment]
Yeah, we have found the same problem in the past, but since the fix is so simple, we decided that it's better to bundle the latest officially released version of the library instead, and let individual implementations that need the master version just add it to the project's requirements.

Glad you found this useful @sfeilmeier, if you think any part of the docs can be improved, please open a PR for the README and we can consider it 😉
