### ISSUE TITLE
With versions != 8.0, the QWeb reports didn't work.

### ISSUE THREAD

**Issue by joserprieto** [Tecnativa/docker-odoo-base#106]
The problem is reported for Odoo:

https://github.com/odoo/odoo/issues/2934

https://github.com/odoo/odoo/issues/1105

As the port mapping, in versions differents of 8.0, is 9069 -> 8069, and so on, we need to add the "report.url" parameter on the system parameters:

```
report.url
http://127.0.0.1:8069
```
Example on a v. 10 installation:

![image](https://user-images.githubusercontent.com/1142233/34363321-4f9cfdf8-ea7b-11e7-8af3-bbaabbcfa0d9.png)

Is the same "problem" as we use a proxy between Odoo and the outside world.

Maybe other options are more cleaner, i don't know; this works  for me.

Regards.

**Comment by pedrobaeza** [comment]
For production, the parameter is still `http://127.0.0.1:8069` AFAIK

**Comment by joserprieto** [comment]
For production, depends if on prod.yaml file is defined the port mapping; and the same for test, with test.yaml.

The two files haven't defined any port mapping, so, the containers expose the default port (8069 and so on).

Has to be tested, but i think that in test and production environments, the bug for versións != 8.0 is not present, for the default mapping (because from the installation, the `web.base.url` has to be `http://127.0.0.1:8069`).

Maybe you can test it, @pedrobaeza?

Regards.

**Comment by pedrobaeza** [comment]
For the localhost (127.0.0.1), the port is always 8069, no matter which version you use. Externally (with devel.yaml), it's when the port changes per version.

**Comment by joserprieto** [comment]
Then, may be a good choice to include this information on the README.

**Comment by joserprieto** [comment]
(if you want, i make the PR)

**Comment by pedrobaeza** [comment]
Well, I'm not sure what do you want to highlight in the documentation...

**Comment by joserprieto** [comment]
Something like that:

> ## FAQ
> 
> 
> (...)
> 
> ### I get an error with the QWeb reports (Invoices, Sale Ordes, and so on).
> 
> This isn't an error; is because the port mapping of devel environment; as you can view on the devel.yml file, the port mapping is done on this form:
> 
> ```yml
> services:
>     odoo:
> ...
>         ports:
>             - "127.0.0.1:${ODOO_MAJOR}069:8069"
>             - "127.0.0.1:${ODOO_MAJOR}072:8072"
>             - "127.0.0.1:6899:6899"
> ```
> 
> So, for versions != 8.0, the port of Odoo is different inside the container, and outside of them.
> 
> This is a problem that happend with reverse proxy and similar, reported and fixed:
> 
> odoo/odoo#2934
> 
> odoo/odoo#1105
> 
> All you have to do, is add the `report.url` parameter on the system parameters:
> 
> ```
> report.url
> http://127.0.0.1:8069
> ```

Feel free to add directly if you line :smiley: 

Regards.

**Comment by Lourido** [comment]
Hi Pedro, José and all of you,

I have a problem with the PDF documents. I’m desperate and find a solution. You seem to have solved it, Pedro, but the solution does not work for me and I do not know why. Any help would be highly appreciated. Thanks a lot.

I work with Odoo 9 in a Linux CentOS 7.3 in a Mac OS Sierra.
The server has neither proxy nor firewall.
Wkhtmltopdf version 0.12.1 (with patched qt)

This is the configuration of the parameters:
![0](https://user-images.githubusercontent.com/23460076/38867202-9f2b28e8-4243-11e8-94fe-5892ab65eb95.jpeg)

I’ve included “web.base.url.freeze” to make the web.base.url fix (otherwise when you enter in Odoo it’s value changes).

I’ve got the following result:

FIRST IMAGE: correct (pictures, header and footer)
SECOND IMAGE: wrong (the picture is correct but the format, table, size, ... is lost)
![0 invoice wright](https://user-images.githubusercontent.com/23460076/38867364-17de8122-4244-11e8-910f-02ac4b467f7f.png)
![0 certi_mal](https://user-images.githubusercontent.com/23460076/38867465-6fe90090-4244-11e8-9efe-08d7b8c26bca.png)

Same configuration, if I make a change in the file addons/report/models/report.py
Replacing the line: 
#         base_url = irconfig_obj.get_param(cr, SUPERUSER_ID, 'report.url') or irconfig_obj.get_param(cr, SUPERUSER_ID, 'web.base.url')

for the line:
base_url = self.pool['ir.config_parameter'].get_param(cr, uid, 'web.base.url.report')

I’ve got the following reports:

FIRST WRONG: No header, no footer, no css, ...
RIGHT 100% CORRECT but close: the format is correct but it does not print the image (as it did before)

![0 factura mal](https://user-images.githubusercontent.com/23460076/38867600-bbf4cafa-4244-11e8-98e3-d0b57247745b.png)
![0 certi corr](https://user-images.githubusercontent.com/23460076/38867685-03dd568e-4245-11e8-9337-1728c8577149.png)

Of course, I need both 100% correct and at the same time ...

Thanks a lot.

**Comment by pedrobaeza** [comment]
The problem seems to be with your report, not with Odoo itself. Any way, you are doing this on a devel environment?

**Comment by Lourido** [comment]
I've got the same result working on a development or user environment.
Do you mean that the report´s configuration is wrong? Could it be that simple?

**Comment by pedrobaeza** [comment]
It seems you are importing some external CSS/resource, and it fails. Remember that in devel/test environments, networks are isolated and thus, external resources can't be loaded. That's why we put an internal network on the url.

**Comment by Lourido** [comment]
Is there anything I should check at a server level?

**Comment by pedrobaeza** [comment]
Maybe if there's another thing in your network that is blocking some requests, but we can't help anymore with a non derived problem with this.

**Comment by Lourido** [comment]
Quisiera crear un fichero log con las instrucciones que se ejecutan al crear el pdf. Quizás así pueda ver en dónde esta el error. ¿Se puede hacer?

**Comment by joserprieto** [comment]
Do you try to set the loglevel on the dev environment?

As @pedrobaeza said, i think that is a problem with the CSS used, or something like that.

Maybe this links can help you:

https://github.com/odoo/odoo/issues/17897

https://github.com/odoo/odoo/issues/1105

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2225
