### ISSUE TITLE
kaptan requirements issue

### ISSUE THREAD

**Issue by gdgellatly** [Tecnativa/docker-odoo-base#155]
Hi,

I'm not sure what package introduces the issue in the scaffolding, but essentially a sub dependency of one of the files in default scaffolding is kaptan.  Pip installs with --upgrade which installs kaptan 0.5.10 which then isn't compatible with the latest version pinnings of yaml for python < 3.7. EDIT: v11 obviously

So odoo fails to start with either a requests of urllib failure.

Adding kaptan==0.5.9 to top of scaffolding requirements file resolved the issue for me.

**Comment by Yajo** [comment]
Do you have logs?

**Comment by gdgellatly** [comment]
@Yajo sorry I don't.  It was late, I had to get something out the door so it was kind of like, hit issue, fix, then worry about it.

It was a straightforward vanilla dev pull for a new client.  Only xlsxwriter added.

Dockerfile
```
# XXX Base version must match $ODOO_VERSION in .env file
FROM tecnativa/odoo-base:11.0
MAINTAINER Graeme Gellatly <graeme@o4sb.com>
```
pip.txt
```
checksumdir
git+https://github.com/OCA/openupgradelib.git@master
unicodecsv
unidecode
xlsxwriter
```
Nothing else.

**Comment by Yajo** [comment]
I see. I can observe [the log repeatedly in our CI builds](https://travis-ci.org/Tecnativa/docker-odoo-base/jobs/403039998#L2659):

    kaptan 0.5.10 has requirement PyYAML<4,>=3.13, but you'll have pyyaml 3.12 which is incompatible.

It seems kaptan is a requirement for `git-aggregator`, and its requirement is more up to date than Odoo's. [We install 3.12 because that's what Odoo asks for](https://travis-ci.org/Tecnativa/docker-odoo-base/jobs/403039998#L2159):

    Collecting PyYAML==3.12 (from -r https://raw.githubusercontent.com/OCA/OCB/11.0/requirements.txt (line 30))

I opened these pull requests:
- https://github.com/odoo/odoo/pull/25937 for odoo master
- https://github.com/OCA/OCB/pull/768 for OCB 11.0

In any case, the difference from PyYAML 3.12 to 3.13 will mean nothing for us, since it's only adding Python 3.7 support, and currently Doodba 11.0 builds are frozen in Python 3.5. Just an ugly warning, so I'll close this.

Thanks!
