### ISSUE TITLE
Issues with wkhtmltopdf

### ISSUE THREAD

**Issue by bosd** [Tecnativa/docker-odoo-base#80]
Hi,
On the reports generated on the V10 odoo instances the headers and footers are not correctly displayed.
It seems that wkhtmltopdf is not correctly installed in the container.

The Dockerfile however points to the wkhtmltopdf repo and version 0.12.4.

However odoo recommend version 0.12.1 from their server.
http://www.odoo.com/documentation/10.0/setup/install.html #

**Comment by lasley** [comment]
Odoo is recommending an out of date version with known security issues.

Can you elaborate on what is not working with the header and footers?

**Comment by bosd** [comment]
Thanks for the explanation.
I am using the ootb dockerfile, 
When I genereate an report the header is not displayed at all.
The footer is part off shown on the bottom, but the outline is not correct.
The bullet lists in the footer is expanding to below the page.

**Comment by Yajo** [comment]
Hi there, indeed wkhtmltopdf is very awful in many things, but after many tests, we found the latest version to be the most reliable in terms of stability and security, as @lasley pointed out. That's why that's the one we bundle.

After all, at some point you'd have to update your reports, so do it now and get the benefits of the newer version.

OTOH, if you prefer to stick with an older version, for this project of yours that fails to render, no problem. That's the magic of Docker, right? Just [copy the logic used to install this version](https://github.com/Tecnativa/docker-odoo-base/blob/8d8c02f852406920e5fe08a64772a0cf6a1782a4/Dockerfile#L118-L123) into [a `build.d` script](https://github.com/Tecnativa/docker-odoo-base#optodoocustombuildd) that replaces it with the one you need in your project.

**Comment by lasley** [comment]
Note that the 0.12.1.x versions aren't available on Github though because they're EOL, so the URL is different and it's zipped using `tar.xz` instead of just tar. This means the logic is different.

There is a PR [here](https://github.com/OCA/maintainer-quality-tools/pull/481/) that has some logic that could be recycled though.
