### ISSUE TITLE
Setup dir triggers duplicate addon in addons.yaml

### ISSUE THREAD

**Issue by PCatinean** [Tecnativa/docker-odoo-base#91]
If one adds more than one oca addons in addons.yaml with "*" execution will stop with

 `Addon setup defined in several repos set(['oca-website', 'oca-web'])`

https://github.com/Tecnativa/docker-odoo-base/blob/cffc52ce4a2bc8e45b9c823998fa5c5ef29ad43d/lib/odoobaselib/__init__.py#L93

Also in case there are multiple addons that shadow eachother, is there no way to bypass the error? Wouldn't a warning be better suited?

**Comment by Yajo** [comment]
> Addon setup defined in several repos set(['oca-website', 'oca-web'])

We should skip the special `setup` directory then. 🤔 

> Also in case there are multiple addons that shadow eachother, is there no way to bypass the error? 

Yes, you can define addons explicitly instead of using `"*"`, such as:

```yaml
repo1:
  - addon1
repo2:
  - addon2
```

> Wouldn't a warning be better suited?

Nope, addons are unsorted. If we have it defined in several places, different addons can get linked in different builds, which would lead to surprises. You just can't define an addon with the same name twice in the same hierarchy level (extra, in this case).

**Comment by PCatinean** [comment]
@Yajo I think the problem is that it just takes directory names, maybe we should do a check if the directory is an actual odoo module before considering / linking it? I'll try to propose a fix if I get some time.

**Comment by Yajo** [comment]
Yeah, it could be a good fix too

**Comment by Yajo** [comment]
Fixed in #93
