### ISSUE TITLE
Use dev enviroment with git repos

### ISSUE THREAD

**Issue by DarioLodeiros** [Tecnativa/docker-odoo-base#99]
The private folder is intended to directly save the modules (not a repository), and the repos folders are rebuilt every time we launch the docker-compose -f setup-devel run... overwriting any change that you do not have uploaded to the repository.
If I'm developing in local with git repo, I must use the private folder?... other volume? 

Thanks!

**Comment by Yajo** [comment]
Private folder is for addons used only in current project, not in any other. If addons are to be shared among more than 1 project, they should go into a separate addons-only repository, which should get linked in both projects through repos.yaml+addons.yaml system.

If you are developing in an external repository created by the setup-devel step, then you should add your changes to the remote in a PR or branch and add the branch/pr to repos.yaml so when you run setup-devel again it aggregates those changes.

**Comment by DarioLodeiros** [comment]
Then... If We want, for example, new repo, We must be sure that we have all the changes uploaded before updating the repos.yaml (becouse we are developing directly on the src repos subfolder)... otherwise, we would lose the changes when the system was rebuilt.
I thought that it could be interesting has a dev folder with the same priority as the private folder, that allows us to update repos without losing changes in local... 
If you think it can be interesting, I can look at that small addition, if I miss something... let me keep investigating... maybe there is something that I am not understanding well yet ;P

**Comment by Yajo** [comment]
Well, the point here is that the project's apprach is production-first, so your devel environment is just production with locally-mounted editable code.

You are supposed to edit all code in devel, including code in `private` and code in cloned repositories. However, in production, a brand new docker image is built for each commit, so in devel you must make sure all code you changed in external repos is going to land in the image, and that's achieved by adding the aggregation instructions in `repos.yaml`.

Usually you only run `setup-devel` in your devel environment when you really need to *reset all code* to make it mirror production. But that's not always the case because it's quite common to have several development branches in each cloned repo.

**Comment by DarioLodeiros** [comment]
Thank you so much!
I learn a new thing and more doubts come to me ;)
I do not know if you have a training session scheduled for this? To see more thoroughly...

**Comment by Yajo** [comment]
We offer trainings on demand, in Spanish or English. You can hire us in https://www.tecnativa.com/page/contactus 😊
